### ISSUE TITLE
Fix issues blocking setuptools upgrade

### ISSUE THREAD

**Issue by tmpayton** [fecgov/marshmallow-pagination#18]
There are issues blocking the upgrade of setuptools >= 71. 

When upgrading to v71 we get the following error: 

  × Running setup.py install for marshmallow-pagination did not run successfully.
  │ exit code: 1
  ╰─> [42 lines of output]
      running install
      /home/circleci/project/.env/lib/python3.10/site-packages/setuptools/_distutils/cmd.py:66: SetuptoolsDeprecationWarning: setup.py install is deprecated.
      !!
      
              ********************************************************************************
              Please avoid running ``setup.py`` directly.
              Instead, use pypa/build, pypa/installer or other
              standards-based tools.
      
              See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
              ********************************************************************************
      
      !!
        self.initialize_options()
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-req-build-9kkamsvz/setup.py", line 37, in <module>
          setup(
        File "/home/circleci/project/.env/lib/python3.10/site-packages/setuptools/__init__.py", line 108, in setup
          return distutils.core.setup(**attrs)
        File "/home/circleci/project/.env/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 184, in setup
          return run_commands(dist)
        File "/home/circleci/project/.env/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 200, in run_commands
          dist.run_commands()
        File "/home/circleci/project/.env/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 970, in run_commands
          self.run_command(cmd)
        File "/home/circleci/project/.env/lib/python3.10/site-packages/setuptools/dist.py", line 956, in run_command
          super().run_command(command)
        File "/home/circleci/project/.env/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.ensure_finalized()
        File "/home/circleci/project/.env/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 111, in ensure_finalized
          self.finalize_options()
        File "/home/circleci/project/.env/lib/python3.10/site-packages/setuptools/command/install.py", line 62, in finalize_options
          super().finalize_options()
        File "/home/circleci/project/.env/lib/python3.10/site-packages/setuptools/_distutils/command/install.py", line 407, in finalize_options
          'dist_fullname': self.distribution.get_fullname(),
        File "/home/circleci/project/.env/lib/python3.10/site-packages/setuptools/_core_metadata.py", line 266, in get_fullname
          return _distribution_fullname(self.get_name(), self.get_version())
        File "/home/circleci/project/.env/lib/python3.10/site-packages/setuptools/_core_metadata.py", line 284, in _distribution_fullname
          canonicalize_version(version, strip_trailing_zero=False),
      TypeError: canonicalize_version() got an unexpected keyword argument 'strip_trailing_zero'
      [end of output]

When upgrading to v72 we get the following error: 

  DEPRECATION: marshmallow-pagination is being installed using the legacy 'setup.py install' method, because it does not have a 'pyproject.toml' and the 'wheel' package is not installed. pip 23.1 will enforce this behaviour change. A possible replacement is to enable the '--use-pep517' option. Discussion can be found at https://github.com/pypa/pip/issues/8559

**Comment by cnlucas** [comment]
Upgrading to latest setuptools no longer causes an issue, they switched to pyproject.toml last year
